### ISSUE TITLE
Duplicated browserSync import

### ISSUE THREAD

**Issue by ZeroX-DG** [simeg/gulpfile-generator#13]
The bug appears when I generate the project with the option dev server set to true. After the generation, the gulpfile.js contains a duplicated browserSync import. 

Pull request is on the way ;) BTW, I like this project :)

**Comment by simeg** [comment]
Hi @ZeroX-DG.

I think I remember this bug. When I saw it though I was in the middle of this project so I didn't feel like fixing it.

Thanks for the PR! I'll look into why Travis is failing.

**Comment by ZeroX-DG** [comment]
I think the reason that Travis is failing is probably related to this issue https://github.com/substack/node-mkdirp/pull/110

**Comment by simeg** [comment]
Fixed with PR #15.
