### ISSUE TITLE
cli error

### ISSUE THREAD

**Issue by ConceptCodes** [simeg/gulpfile-generator#22]
when i run the cli tool it does not exit out.

```
Your project folder is now ready!
1) npm run setup
2) gulp
```` 
it stays on that screen no matter how many times I press CTRL+C

**Comment by simeg** [comment]
Hi @ConceptCodes.

I just tested it and it works as expected on my computer. 

1) What OS are you running?
2) What npm version do you have?
3) What if you run with the dry-run flag? `-n`
4) The CLI functionality comes from the [Inquirer.js](https://github.com/SBoudrias/Inquirer.js) repo, if your setup differs from mine and we can reproduce then we could submit a bug report.
